CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE personals (
  id INT AUTO_INCREMENT NOT NULL,
  personalName VARCHAR(100),
  personalEmail VARCHAR(150) NOT NULL,
  password VARCHAR(10) NOT NULL,
  phone VARCHAR(10),
  CONSTRAINT PERSONALS PRIMARY KEY(id)
);CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  userFullName VARCHAR(250),
  userEmail VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  phone VARCHAR(20),
  CONSTRAINT USERS PRIMARY KEY(id)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT NOT NULL,
  customerFullName VARCHAR(250),
  customerEmail VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER PRIMARY KEY(id, customerFullName)
);